// CREATE a new structure extended file, append some records and
// then CREATE FROM this file a new database file

SET DATE German

CREATE template
APPEND BLANK
FIELD->FIELD_NAME := "ADRNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "BERTADRNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KREDNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 5
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "GEWERK1"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 3
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "GEWERK2"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 3
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "GEWERK3"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 3
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "STATUS"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "AENDDAT"
FIELD->FIELD_TYPE := "D"     
FIELD->FIELD_LEN  := 8    
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "ANREDE"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "TITEL"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "FIRMA"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 30
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "NAME"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 30
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "SORTNAME"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 20
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "VORNAME"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 15      
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "STRASSE"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 30 
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "PLZ"
FIELD->FIELD_TYPE := "N"     
FIELD->FIELD_LEN  := 5      
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "ORT"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 34     
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "TELVW"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 5      
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "TELDW"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 9   
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "KZUEBER"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 1   
FIELD->FIELD_DEC  := 0     
APPEND BLANK
FIELD->FIELD_NAME := "INFO"
FIELD->FIELD_TYPE := "M"     
FIELD->FIELD_LEN  := 10     
FIELD->FIELD_DEC  := 0      
CLOSE
CREATE HWADRES FROM template

USE HWADRES

CLOSE