// CREATE a new structure extended file, append some records and
// then CREATE FROM this file a new database file

CREATE template
APPEND BLANK
FIELD->FIELD_NAME := "FUNKTION"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "FIL_AKT"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ZWEIGST"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 3
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE1"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE2"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE3"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 5
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE4"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE5"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KURZTEXT"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 25      
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "LANGTEXT"
FIELD->FIELD_TYPE := "M"     
FIELD->FIELD_LEN  := 10     
FIELD->FIELD_DEC  := 0      
CLOSE
CREATE HWADRES FROM template

USE HWADRES
APPEND BLANK
CLOSE