// CREATE a new structure extended file, append some records and
// then CREATE FROM this file a new database file

SET DATE German

CREATE template
APPEND BLANK
FIELD->FIELD_NAME := "ANGEBOTSNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "INTERESSNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "OBJEKTNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KZ_ERFASS"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KZ_HS_GES"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ANL_DAT"
FIELD->FIELD_TYPE := "D"     
FIELD->FIELD_LEN  := 8    
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "ANL_PERS"
FIELD->FIELD_TYPE := "N"     
FIELD->FIELD_LEN  := 4   
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "AEND_DAT"
FIELD->FIELD_TYPE := "D"     
FIELD->FIELD_LEN  := 8    
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "AEND_PERS"
FIELD->FIELD_TYPE := "N"     
FIELD->FIELD_LEN  := 4   
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KD_NAME"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 20 
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KD_STRASSE"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 25
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KD_PLZ"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 4
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KD_ORT"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 20
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "BAU_STR"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 25
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "BAU_PLZ"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 4
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "BAU_ORT"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 20
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "V_ART"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "HAUSART"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 3
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "HEIZ_ANZ"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "EINH_ANZ"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "DACHART"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "DACHAUSBAU"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ANZ_KG"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ANZ_UG"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ANZ_EG"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ANZ_OG"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ANZ_DG"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 1
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "HEIZART"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 3
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "HUMUSFLAEC"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 7
FIELD->FIELD_DEC  := 2
APPEND BLANK
FIELD->FIELD_NAME := "AUSSENFL"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 7
FIELD->FIELD_DEC  := 2
APPEND BLANK
FIELD->FIELD_NAME := "INNENFL"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 7
FIELD->FIELD_DEC  := 2
APPEND BLANK
FIELD->FIELD_NAME := "BODENPL_FL"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 7
FIELD->FIELD_DEC  := 2
APPEND BLANK
FIELD->FIELD_NAME := "AUSHUB_FL"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 7
FIELD->FIELD_DEC  := 2
CLOSE

CREATE KAKUNDE FROM template

USE KAKUNDE
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->INTERESSNR := 0
FIELD->OBJEKTNR   := 0
FIELD->KZ_ERFASS  := " "
FIELD->KZ_HS_GES  := " "
FIELD->ANL_DAT    := CTOD("10.06.1987")
FIELD->ANL_PERS   := 522 
FIELD->AEND_DAT   := CTOD("10.06.1987")
FIELD->AEND_PERS  := 522 
FIELD->KD_NAME    := "Krieger Josef"
FIELD->KD_STRASSE := "Destouchesstr. 35"
FIELD->KD_PLZ     := 8000
FIELD->KD_ORT     := "München 40"
FIELD->V_ART      := "B"
FIELD->HAUSART    := "EFH"
FIELD->HEIZ_ANZ   := 1
FIELD->EINH_ANZ   := 1
FIELD->DACHART    := "AA"
FIELD->DACHAUSBAU := "J"
FIELD->ANZ_KG     := 1
FIELD->ANZ_UG     := 0
FIELD->ANZ_EG     := 1
FIELD->ANZ_OG     := 1
FIELD->ANZ_DG     := 1
FIELD->HEIZART    := "OEL"

CLOSE ALL