// CREATE a new structure extended file, append some records and
// then CREATE FROM this file a new database file

CREATE template
APPEND BLANK
FIELD->FIELD_NAME := "ANGEBOTSNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "FUNKTION"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "REIHE"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ANZAHL"
FIELD->FIELD_TYPE := "N"     
FIELD->FIELD_LEN  := 6    
FIELD->FIELD_DEC  := 2      
CLOSE
CREATE KBHAUSD FROM template


USE KBHAUSD
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "AUSSCHWAAG"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 13.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "AUSSCHWAAG"
FIELD->REIHE      := 2
FIELD->ANZAHL     := 6.50
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "MANSARDE"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 12.30
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "MANSARDE"
FIELD->REIHE      := 2
FIELD->ANZAHL     := 6.70
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "BALKWAAG"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 3.50
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "BALKWAAG"
FIELD->REIHE      := 2
FIELD->ANZAHL     := 5.20
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "2KAMINML"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 9.80
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "BADEWANNE"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 2.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "DUSCHWANNE"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 1.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "WASCHBECK"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 4.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "HANDWASCH"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 1.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "WCSCHšSSEL"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 2.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "BADUMFANG"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 14.20
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "BADUMFANG"
FIELD->REIHE      := 2
FIELD->ANZAHL     := 10.50
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "BADFLŽCHE"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 12.45
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "BADFLŽCHE"
FIELD->REIHE      := 2
FIELD->ANZAHL     := 3.75
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "WCFLŽCHE"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 2.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "KšCHENFL"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 13.20
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "KGVORPLATZ"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 4.50
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "HEIZFL"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 13.00
APPEND BLANK
FIELD->ANGEBOTSNR := 9998700001
FIELD->FUNKTION   := "ANZTANK"
FIELD->REIHE      := 1
FIELD->ANZAHL     := 1.00
CLOSE