// CREATE a new structure extended file, append some records and
// then CREATE FROM this file a new database file

CREATE template
APPEND BLANK
FIELD->FIELD_NAME := "ANGEBOTSNR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "GESCH_ART"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "GESCH_NR"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "FUNKTION"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "REIHE"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "DX"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 7
FIELD->FIELD_DEC  := 3
APPEND BLANK
FIELD->FIELD_NAME := "DY"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 7
FIELD->FIELD_DEC  := 3
APPEND BLANK
FIELD->FIELD_NAME := "WINKEL"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 4
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "HOEHE"
FIELD->FIELD_TYPE := "N"     
FIELD->FIELD_LEN  := 5      
FIELD->FIELD_DEC  := 2
APPEND BLANK
FIELD->FIELD_NAME := "TYP"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 5     
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "ANST_ABM"
FIELD->FIELD_TYPE := "N"     
FIELD->FIELD_LEN  := 4    
FIELD->FIELD_DEC  := 2      
APPEND BLANK
FIELD->FIELD_NAME := "TYP_ABM"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 5    
FIELD->FIELD_DEC  := 0      
CLOSE
CREATE KC-GESCH FROM template
