// CREATE a new structure extended file, append some records and
// then CREATE FROM this file a new database file

CREATE template
APPEND BLANK
FIELD->FIELD_NAME := "FUNKTION"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "FIL_AKT"
FIELD->FIELD_TYPE := "N"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "ZWEIGST"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 3
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE1"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE2"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 10
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE3"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 5
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE4"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "CODE5"
FIELD->FIELD_TYPE := "C"
FIELD->FIELD_LEN  := 2
FIELD->FIELD_DEC  := 0
APPEND BLANK
FIELD->FIELD_NAME := "KURZTEXT"
FIELD->FIELD_TYPE := "C"     
FIELD->FIELD_LEN  := 25      
FIELD->FIELD_DEC  := 0      
APPEND BLANK
FIELD->FIELD_NAME := "LANGTEXT"
FIELD->FIELD_TYPE := "M"     
FIELD->FIELD_LEN  := 10     
FIELD->FIELD_DEC  := 0      
CLOSE
CREATE AACODE FROM template

USE AACODE
APPEND BLANK
FIELD->FUNKTION := "ANREDE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "A"
FIELD->KURZTEXT := "Herr"
APPEND BLANK
FIELD->FUNKTION := "ANREDE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "B"
FIELD->KURZTEXT := "Frau"
APPEND BLANK
FIELD->FUNKTION := "ANREDE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "C"
FIELD->KURZTEXT := "Fr„ulein"
APPEND BLANK
FIELD->FUNKTION := "ANREDE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "D"
FIELD->KURZTEXT := "Firm"
APPEND BLANK
FIELD->FUNKTION := "ANREDE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "E"
FIELD->KURZTEXT := "Damen und Herren"
APPEND BLANK
FIELD->FUNKTION := "TITEL"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "H"
FIELD->KURZTEXT := "Dipl.Kfm"
APPEND BLANK
FIELD->FUNKTION := "TITEL"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "I"
FIELD->KURZTEXT := "Dipl.Ing"
APPEND BLANK
FIELD->FUNKTION := "TITEL"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "J"
FIELD->KURZTEXT := "Dr"
APPEND BLANK
FIELD->FUNKTION := "TITEL"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "K"
FIELD->KURZTEXT := "Prof."
APPEND BLANK
FIELD->FUNKTION := "HERKUNFT"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "AA"
FIELD->KURZTEXT := "Sddeutsche Zeitung"
APPEND BLANK
FIELD->FUNKTION := "HERKUNFT"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "AB"
FIELD->KURZTEXT := "Nrnberger Nachrichten"
APPEND BLANK
FIELD->FUNKTION := "HERKUNFT"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "BA"
FIELD->KURZTEXT := "Das Bauen"
APPEND BLANK
FIELD->FUNKTION := "HERKUNFT"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "BB"
FIELD->KURZTEXT := "Sch”ner Wohnen"
APPEND BLANK
FIELD->FUNKTION := "HERKUNFT"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "BC"
FIELD->KURZTEXT := "Fertighaus"
APPEND BLANK
FIELD->FUNKTION := "PROJEKTTYP"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "AA001"
FIELD->KURZTEXT := "MODELL A1"
APPEND BLANK
FIELD->FUNKTION := "PROJEKTTYP"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "AA002"
FIELD->KURZTEXT := "MODELL A2"
APPEND BLANK
FIELD->FUNKTION := "PROJEKTTYP"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "AA003"
FIELD->KURZTEXT := "MODELL A3"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "AH"
FIELD->KURZTEXT := "Althaus"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "NB"
FIELD->KURZTEXT := "Neubau"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "AP"
FIELD->KURZTEXT := "Arch./Planungsbï¿½ro"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "SS"
FIELD->KURZTEXT := "Schornsteinfeger"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "BU"
FIELD->KURZTEXT := "Bauunternehmer"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "FH"
FIELD->KURZTEXT := "Fertighaus"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "IM"
FIELD->KURZTEXT := "Immobilien"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "HB"
FIELD->KURZTEXT := "Heizungsbau"
APPEND BLANK
FIELD->FUNKTION := "ZIELGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "BT"
FIELD->KURZTEXT := "Bautr„ger"
APPEND BLANK
FIELD->FUNKTION := "PRODGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "OK"
FIELD->KURZTEXT := "Offener Kamin"
APPEND BLANK
FIELD->FUNKTION := "PRODGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "KK"
FIELD->KURZTEXT := "Kachelkamin"
APPEND BLANK
FIELD->FUNKTION := "PRODGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "KO"
FIELD->KURZTEXT := "Kachelofen"
APPEND BLANK
FIELD->FUNKTION := "PRODGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "HK"
FIELD->KURZTEXT := "Heizkamin"
APPEND BLANK
FIELD->FUNKTION := "PRODGRUPPE"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "SO"
FIELD->KURZTEXT := "Sonstiges"
APPEND BLANK
FIELD->FUNKTION := "FILIALE"
FIELD->FIL_AKT := 1
FIELD->CODE1 := " "
FIELD->KURZTEXT := "VERKAUFSHAUS 1"
APPEND BLANK
FIELD->FUNKTION := "FILIALE"
FIELD->FIL_AKT := 2
FIELD->CODE1 := " "
FIELD->KURZTEXT := "VERKAUFSHAUS 2"
APPEND BLANK
FIELD->FUNKTION := "FILIALE"
FIELD->FIL_AKT := 3
FIELD->CODE1 := " "
FIELD->KURZTEXT := "VERKAUFSHAUS 3"
APPEND BLANK
FIELD->FUNKTION := "FILIALE"
FIELD->FIL_AKT := 4
FIELD->CODE1 := " "
FIELD->KURZTEXT := "VERKAUFSHAUS 4"
APPEND BLANK
FIELD->FUNKTION := "FILIALE"
FIELD->FIL_AKT := 5
FIELD->CODE1 := " "
FIELD->KURZTEXT := "VERKAUFSHAUS 5"
APPEND BLANK
FIELD->FUNKTION := "FILIALE"
FIELD->FIL_AKT := 6
FIELD->CODE1 := " "
FIELD->KURZTEXT := "VERKAUFSHAUS 6"
APPEND BLANK
FIELD->FUNKTION := "GEBIET"
FIELD->FIL_AKT := 1
FIELD->CODE1 := " "
FIELD->KURZTEXT := "01020304"
APPEND BLANK
FIELD->FUNKTION := "GEBIET"
FIELD->FIL_AKT := 2
FIELD->CODE1 := " "
FIELD->KURZTEXT := "2335462127"
APPEND BLANK
FIELD->FUNKTION := "ANREDE2"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "A"
FIELD->KURZTEXT := "r Herr"
APPEND BLANK
FIELD->FUNKTION := "ANREDE2"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "B"
FIELD->KURZTEXT := " Frau"
APPEND BLANK
FIELD->FUNKTION := "ANREDE2"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "C"
FIELD->KURZTEXT := "s Fr„ulein"
APPEND BLANK
FIELD->FUNKTION := "ANREDE2"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "D"
FIELD->KURZTEXT := " Damen und Herren"
APPEND BLANK
FIELD->FUNKTION := "ANREDE2"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "E"
FIELD->KURZTEXT := " Damen und Herren"
APPEND BLANK
FIELD->FUNKTION := "GEWERK"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "100"
FIELD->KURZTEXT := "Testgewerk 1"
APPEND BLANK
FIELD->FUNKTION := "GEWERK"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "101"
FIELD->KURZTEXT := "Testgewerk 2"
APPEND BLANK
FIELD->FUNKTION := "GEWERK"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "102"
FIELD->KURZTEXT := "Testgewerk 3"
APPEND BLANK
FIELD->FUNKTION := "GEWERK"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "103"
FIELD->KURZTEXT := "Testgewerk 4"
APPEND BLANK
FIELD->FUNKTION := "GEWERK"
FIELD->FIL_AKT := 0
FIELD->CODE1 := "104"
FIELD->KURZTEXT := "Testgewerk 5"

CLOSE