STORE " 1"                    TO QZWSTNR
STORE "VERKAUFSHAUS MšNCHEN"  TO QZWSTNAME
STORE "DESTOUCHESSTR. 35"     TO QZWSTSTR
STORE "8000 MšNCHEN"          TO QZWSTORT
STORE "089/3008220"           TO QZWSTTEL

SAVE TO QZWST

RELEASE ALL

STORE 1                    TO UPSNR
STORE "MERCK"              TO UNACHNAME
STORE "08"                 TO UTAETIG

SAVE TO USER

RELEASE ALL

RESTORE FROM QZWST
RESTORE FROM USER ADDITIVE
* DISPLAY MEMORY
